print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/m/Documents/QueensU/CISC 226/TeamRocket/PerceptionTest/Assets/mesh/block_exit.mb"`)
{		
	file -o "/Users/m/Documents/QueensU/CISC 226/TeamRocket/PerceptionTest/Assets/mesh/block_exit.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/m/Documents/QueensU/CISC 226/TeamRocket/PerceptionTest/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/m/Documents/QueensU/CISC 226/TeamRocket/PerceptionTest/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/m/Documents/QueensU/CISC 226/TeamRocket/PerceptionTest/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
